import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Logo from "../assets/images/header-logo.svg";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="header">
          <div className="cont">
            <div className="flex items-center justify-between">
              <div className="logo">
                <Image src={Logo} alt="svg pixl logo" />
              </div>
              <div className="menus">
                <ul className="text-2xl flex gap-[50px] items-center">
                  <li>
                    <Link href="/api">API</Link>
                  </li>
                  <li>
                    <Link href="/blog">Blog</Link>
                  </li>
                  <li>
                    <Link href="/weather">Weather</Link>
                  </li>
                  <li>
                    <Link href="/payment">Payment</Link>
                  </li>
                  <li>
                    <Link href="/search">Search</Link>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
